hunter_config(Protobuf VERSION ${HUNTER_Protobuf_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)
hunter_config(Boost VERSION ${HUNTER_Boost_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)
hunter_config(gflags VERSION ${HUNTER_gflags_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)
hunter_config(OpenCV VERSION ${HUNTER_OpenCV_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)

hunter_config(PNG VERSION ${HUNTER_PNG_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)
hunter_config(jasper VERSION ${HUNTER_jasper_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)
hunter_config(Jpeg VERSION ${HUNTER_Jpeg_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)
hunter_config(ZLIB VERSION ${HUNTER_ZLIB_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CONFIGURATION_TYPES=Release)
